networks:
  shibboleth-network:
    driver: bridge

services:
  sp-openldap:
    image: osixia/openldap:latest
    container_name: sp-openldap
    restart: unless-stopped
    ports:
      - '389:389'
      - '636:636'
    environment:
      - LDAP_ORGANISATION=ScreenPal
      - LDAP_DOMAIN=ldap-local.screenpal.com
      - LDAP_ROOT=dc=ldap-local,dc=screenpal,dc=com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_ADMIN_DN=cn=admin,dc=ldap-local,dc=screenpal,dc=com
      - LDAP_PORT_NUMBER=389
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '128m'
        reservations:
          memory: '32m'
    volumes:
      - './openldap_data/ldap:/var/lib/ldap'
      - './openldap_data/slapd:/etc/ldap/slapd.d'
  sp-phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: sp-phpldapadmin
    restart: unless-stopped
    ports:
      - '8181:80'
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=sp-openldap
      - PHPLDAPADMIN_HTTPS=false
      - LDAP_ENABLE_TLS=no
    depends_on:
      - sp-openldap
  tomcat:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tomcat_server
    ports:
      - "8080:8080"
    environment:
      - CATALINA_OPTS=-Xms512m -Xmx1024m
      - JAVA_HOME=/opt/java/openjdk  # ✅ Use the correct JAVA_HOME from inside the container
      - PATH=$JAVA_HOME/bin:$PATH
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
      - ./logs:/usr/local/tomcat/logs
      - ./shibboleth-idp:/opt/shibboleth-idp
      - ./idp-webapp:/opt/idp-webapp
      - ./misc:/opt/misc
    entrypoint: ["/bin/sh", "-c",
                 "cp /opt/misc/setenv.sh /usr/local/tomcat/bin/setenv.sh && \
                 mkdir -p /usr/local/tomcat/conf/Catalina/localhost && \
                 cp /opt/misc/idp.xml /usr/local/tomcat/conf/Catalina/localhost/idp.xml && \
                 /opt/shibboleth-idp/bin/build.sh && \
                 cp -R /opt/idp-webapp/* /opt/shibboleth-idp/war && \
                 cd /opt/shibboleth-idp/war && jar -cvf idp.war . && \
                 cp /opt/shibboleth-idp/war/idp.war /usr/local/tomcat/webapps/idp.war && \
                 mkdir -p /opt/shibboleth-idp/session-store && \
                 exec /usr/local/tomcat/bin/catalina.sh run"]
    restart: unless-stopped

volumes:
  openldap_data:
    driver: local
